server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal
    password: letmein
    username: supportportal
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: '!6!!AkgvHsEdXh&xrev!&%#ikEAA$xHhm$X$7$k9oS8w^eDR@ushSmzFmUXGX4QKxbtnX#A'